version: '3'

services:

  uftm:
    depends_on:
      - postgres
    image: mobilelifecycle/uft-digitallab
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      FQDN: uft-mobile

  postgres:
    image: postgres:11.7
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
